[package]
name = "sidecar"
version = "0.1.0"
description = "A Tauri application with a sidecar binary"
edition = "2021"
rust-version = "1.59"

[build-dependencies]
tauri-build = { path = "../../../core/tauri-build", features = ["codegen"] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { path = "../../../core/tauri", features = ["process-command-api", "shell-sidecar"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
