[workspace]
members = [ "node" ]

[package]
name = "tauri-cli"
version = "1.2.2"
authors = [ "Tauri Programme within The Commons Conservancy" ]
edition = "2021"
rust-version = "1.59"
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.app"
repository = "https://github.com/tauri-apps/tauri"
description = "Command line interface for building Tauri apps"
include = [
  "src/",
  "/templates",
  "scripts/",
  "*.json",
  "*.rs",
  "tauri.gitignore",
  "tauri-dev-watcher.gitignore",
  "LICENSE*"
]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/cli.rs-v{ version }/cargo-tauri-{ target }.{ archive-format }"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"

[package.metadata.binstall.overrides.x86_64-apple-darwin]
pkg-fmt = "zip"

[[bin]]
name = "cargo-tauri"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = [ "derive" ] }
anyhow = "1.0"
tauri-bundler = { version = "1.1.2", path = "../bundler" }
colored = "2.0"
once_cell = "1"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
notify = "5.0"
notify-debouncer-mini = "0.2"
shared_child = "1.0"
toml_edit = "0.14"
json-patch = "0.2"
tauri-utils = { version = "1.2.1", path = "../../core/tauri-utils", features = [ "isolation", "schema", "config-json5", "config-toml" ] }
toml = "0.5"
jsonschema = "0.16"
handlebars = "4.3"
include_dir = "0.7"
minisign = "0.7"
base64 = "0.13.0"
ureq = "2.5"
os_info = "3.5"
semver = "1.0"
regex = "1.6.0"
unicode-width = "0.1"
zeroize = "1.5"
heck = "0.4"
dialoguer = "0.10"
url = { version = "2.3", features = [ "serde" ] }
os_pipe = "1"
ignore = "0.4"
ctrlc = "3.2"
log = { version = "0.4.17", features = [ "kv_unstable", "kv_unstable_std" ] }
env_logger = "0.9.1"
icns = { package = "tauri-icns", version = "0.1" }
image = { version = "0.24", default-features = false, features = [ "ico" ] }
axum = { version = "0.5.16", features = [ "ws" ] }
html5ever = "0.25"
kuchiki = "0.8"
tokio = { version = "1", features = [ "macros", "sync" ] }
common-path = "1"

[target."cfg(windows)".dependencies]
winapi = { version = "0.3", features = [ "handleapi", "processenv", "winbase", "wincon", "winnt" ] }

[target."cfg(unix)".dependencies]
libc = "0.2"

[profile.release]
lto = true
