[package]
name = "tauri-plugin-autostart"
version = "0.1.0"
description = "Automatically launch your application at startup."
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
serde_json = "*"
tauri = "*"
log = "*"
thiserror = "*"
auto-launch = "0.4"